name: Check PR

on:
  pull_request:
    types: [closed]

jobs:
  checks-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checks
        run: |
          echo PR "#${{ github.event.number }}"
          echo Head Ref "#${{ github.head_ref }}"
          echo Base Ref "#${{ github.base_ref }}"
      - name: Create a tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "version_pr_${{ github.event.number }}"
